@startuml

title "Flow of Value for mUSD on Polygon"

box Polygon #PowderBlue
actor "User" as user
actor "Swapper" as swapper
participant "Aave" as aave <<Aave>>
participant "Aave\nIntegrator" as int <<mStable>>
participant "Liquidator" as liq <<mStable>>
participant "QuickSwap" as qs <<QuickSwap>>

participant "mAsset\n(mUSD PoS)" as musd <<mStable>>
participant "Savings\nManager" as sm <<mStable>>
participant "Interest\nBearing\nmAsset\n(imUSD)" as imusd <<mStable>>
participant "imUSD Vault\n(v-imUSD)" as vimusd <<mStable>>
participant "Revenue\nRecipient" as rr <<mStable>>
participant "Emissions\nController" as pec <<mStable>>

end box

box Mainnet #Aqua
actor "Operations" as ops
participant "mAsset\n(mUSD)" as emusd <<mStable>>
participant "UniSwap" as uni <<UniSwap>>
participant "Emissions\nController" as ec <<mStable>>
actor "MTA\nStakers" as staker
end box

... **Intraday** ...

group Mint mUSD
user -> musd : USDC, DAI and/or USDT
musd -> int : USDC, DAI and/or USDT
int -> aave : USDC, DAI\nand/or USDT
aave -> int : aUSDC, aDAI\nand/or aUSDT
musd -> user : mUSD
end

group Deposit mUSD
user -> imusd : mUSD
imusd -> user : imUSD
end

group Stake imUSD
user -> vimusd : imUSD
vimusd -> user : v-imUSD
end

group Swap
swapper -> musd : USDC
musd -> musd : 2bps swap fee\nin mUSD
musd -> int : USDC
int -> aave : USDC
aave -> int : cUSDC
int -> aave : aSUSD
aave -> int : sUSD
int -> musd : sUSD
musd -> swapper : sUSD
end

group Redeem mUSD
user -> musd : mUSD
musd -> musd : 2bps fee\nin mUSD
int -> aave : aUSDC, aDAI\nand/or aUSDT
aave -> int : USDC, DAI\nand/or USDT
int -> musd : USDC, DAI and/or USDT
musd -> user : USDC, DAI and/or USDT
end

... **Daily** ...

== Collect Trading Fees, Platform Interest and Platform Rewards ==

group Collect Trading Fees
musd -> sm : mUSD swap and\nredeem fees
sm -> imusd : 90% mUSD
sm -> sm : 10% mUSD gov fee
end

group Collect Platform Interest
aave -> musd : USDC, DAI, USDT and sUSD interest
note left : increased aToken\nexchange rates
musd -> sm : mUSD
sm -> imusd : 90% mUSD\nstreamed over\n1 day
sm -> sm : 10% mUSD gov fee
end

' group Claim Platform Rewards
' aave -> int : WMATIC rewards
' end

' group Liquidate Platform Rewards
' int -> liq : WMATIC
' liq -> qs : WMATIC
' qs -> liq : USDC
' liq -> musd : USDC
' musd -> liq : mUSD
' liq -> sm : mUSD
' sm -> imusd : 90% mUSD\nstreamed over\n1 day
' sm -> sm : 10% mUSD gov fee
' end

... **Monthly** ...

== MTA Emissions to Dials ==

group Distribute Gov Fees
sm -> rr : mUSD gov fees
end

group Buy Back MTA
rr -> ops : mUSD over PoS Bridge
ops -> emusd : mUSD
emusd -> ops : USDC
ops -> uni : USDC
uni -> ops : MTA
ops -> ec : MTA Purchased
end

... **Weekly** ...

group Distribute to Dials
ec -> staker : MTA Purchased\nMTA Emissions
ec -> pec: MTA Emissions over PoS Bridge
pec -> vimusd : MTA
vimusd -> user : MTA
end

@enduml
