@startuml

title "Emissions to Polygon FRAX"

actor Ops as ops

box "Mainnet" #LightGreen
participant "Emissions Controller" as ec <<mStable>>
participant "MTA" as mta <<mStable>>
participant "FRAX\nBridge Forwarder" as bf <<mStable>>
participant "Root\nChain Manager" as rcm <<Polygon>>
end box

participant "PoS Bridge" as b <<Polygon>>

box "Polygon" #LightBlue
participant "Child\nChain Manager" as ccm <<Polygon>>
participant "FRAX Farm\nL2 Bridge Recipient" as cr <<FRAX>>
participant "Polygon MTA" as pmta <<Polygon>>
end box

actor User as user

activate b
b -> rcm : on StateSynced
note right : watch for\nStateSync events

ops -> ec : distributeRewards ([dial ids])
activate ec
ec -> mta: transfer(Root Recipient, rewards)
activate mta
note left: transfer MTA\nfrom Emissions Controller\nto Root Recipient
return
ec -> bf: notifyRewardAmount(rewards)
activate bf
bf -> rcm : depositFor (\nFRAX Farm,\nMTA,\namount)
activate rcm
rcm -> mta : transferFrom (\nRoot Recipient,\nRoot Chain Manager,\namount)
note right : transfer MTA\nfrom Recipient\nto Bridge
activate mta
return
return
note right : emit StateSynced event
return
return

rcm -> b : StateSynced (\nid\nreceiver,\ndata)
b -> ccm : onStateReceived (\nid\nreceiver,\ndata)
activate ccm
ccm -> pmta : deposit (FRAX Farm, amount)
activate pmta
pmta -> pmta : mint ()
note left : mints MTA\nto FRAX Farm
return
return

==== After rewards have accrued ====

user -> cr : getRewards ()
activate cr
cr -> pmta : transfer (\nuser,\nrewards)
activate pmta
note left: transfer MTA\nfrom FRAX Farm\nto User
return
return

@enduml