@startuml

title "Emissions to Polygon Balancer Pool"

actor Ops as ops

box "Mainnet" #LightGreen
participant "Emissions Controller" as ec <<mStable>>
participant "MTA" as mta <<mStable>>
participant "Disperse\nBridge Forwarder" as bf <<mStable>>
participant "Root\nChain Manager" as rcm <<Polygon>>
end box

participant "PoS Bridge" as b <<Polygon>>


box "Polygon" #LightBlue
participant "Child\nChain Manager" as ccm <<Polygon>>
participant "L2 Emissions Controller" as pec <<mStable>>
participant "Bal Rewards\nForwarder" as df <<mStable>>
participant "Polygon MTA" as pmta <<Polygon>>
participant "Streamer" as s <<Balancer>>
participant "Gauge" as bg <<Balancer>>
end box

actor Users as user

activate b
b -> rcm : on StateSynced
note right : watch for\nStateSync events

ops -> ec : distributeRewards ([dial ids])
activate ec
ec -> mta: transfer(Root Recipient, rewards)
activate mta
note left: transfer MTA\nfrom Emissions Controller\nto Root Recipient
return
ec -> bf: notifyRewardAmount(rewards)
activate bf
bf -> rcm : depositFor (\nReward Forwarder,\nMTA,\namount)
activate rcm
rcm -> mta : transferFrom (\nRoot Recipient,\nRoot Chain Manager,\namount)
note right : transfer MTA\nfrom Recipient\nto Bridge
activate mta
return
return
note right : emit StateSynced event
return
return

rcm -> b : StateSynced (\nid\nreceiver,\ndata)
b -> ccm : onStateReceived (\nid\nreceiver,\ndata)
activate ccm
ccm -> pmta : deposit (Reward Forwarder, amount)
activate pmta
pmta -> pmta : mint ()
note left : mints MTA\nto Reward Forwarder
return
return

====

ops -> pec : distributeRewards ([dial ids])
activate pec
pec -> pmta: transfer(Root Recipient, rewards)
activate pmta
note left: transfer MTA\nfrom Emissions Controller\nto End Recipient
return
pec -> df: notifyRewardAmount(rewards)
activate df
df -> pmta : safeTransfer (\nReward Forwarder,\nMTA,\namount)
activate pmta
note right : transfer MTA\nfrom Reward Forwarder\nto Streamer
return
df -> s : notify_reward_amount (\nMTA)
activate s
note right : Stream rewards to\nGauge
s -> bg : stream rewards
activate bg
return
return
return

return

==== After rewards have accrued ====

user -> bg : claimed_reward (\naddr,\nMTA)
activate bg
bg -> pmta : transfer (\nuser,\nrewards)
activate pmta
note left: transfer MTA\nfrom BAL GAUGE\nto User
return
return

@enduml