@startuml

title "Weekly Rewards to Vaults"

actor User as user
actor Ops as ops
participant "Emissions Controller" as ec <<mStable>>
participant "Vaults" as vault <<mStable>>
participant "MTA" as mta <<mStable>>

user -> ec: setVoterDialWeights ([dial ids], [weights])
activate ec
note right: proportions voting power across dials\nfor future distributions
return

==== After Thursday 00:00 UTC ====

ops -> ec : calculateRewards ()
activate ec
note right: Calculates and stores\nrewards for each dial
return

ops -> ec : distributeRewards ([dial ids])
activate ec
loop Dials
ec -> mta: transfer(vault, rewards)
activate mta
note left: transfer MTA\nfrom Emissions Controller\nto Vault
return
ec -> vault: notifyRewardAmount(rewards)
activate vault
note right: Stream MTA to Users
return
end
return

==== After rewards have accrued ====

user -> vault: claimRewards ()
activate vault
vault -> mta: transfer(user, rewards)
activate mta
note left: transfer MTA\nfrom Vault\nto User
return
return

@enduml
