@startuml

title "Save+ Contract Dependencies"

object "Curve3CrvMetaVault" as mv1 <<mStable>> {
    asset: DAI
    symbol: 3pDAI
    name: 3Pooler Meta Vault (DAI)
}

object "Curve3CrvMetaVault" as mv2 <<mStable>> {
    asset: USDC
    symbol: 3pUSDC
    name: 3Pooler Meta Vault (USDC)
}

object "Curve3CrvMetaVault" as mv3 <<mStable>> {
    asset: USDT
    symbol: 3pUSDT
    name: 3Pooler Meta Vault (USDT)
}

object "PeriodicAllocationPerfFeeMetaVault" as mv4 <<mStable>> {
    asset: 3Crv
    symbol: mv3CRV
    name: 3CRV Convex Meta Vault
}

object "Convex3CrvLiquidatorVault" as bv1 <<mStable>> {
    asset: 3Crv
    symbol: vcx3CRV-FRAX
    name:  3CRV Convex FRAX Vault
}

object "Convex3CrvLiquidatorVault" as bv2 <<mStable>> {
    asset: 3Crv
    symbol: vcx3CRV-mUSD
    name: 3Crv Convex mUSD Vault
}

object "Convex3CrvLiquidatorVault" as bv3 <<mStable>> {
    asset: 3Crv
    symbol: vcx3CRV-BUSD
    name: 3Crv Convex BUSD Vault
}

object "Convex3CrvLiquidatorVault" as bv4 <<mStable>> {
    asset: 3Crv
    symbol: vcx3CRV-LUSD
    name: 3Crv Convex LUSD Vault
}

' class "Convex3CrvLiquidatorVault" as bv5 <<mStable>> {
'     asset: 3Crv
'     symbol: v3CRV-CX3
'     name: Convex sUSD Basic Vault
' }

object "Liquidator" as l <<mStable>> {
}

object "CowSwapDex" as css <<mStable>> {
}

object "CowSwap" as cs #LightSkyBlue {
}

object "3Pool" as 3p <<Curve>> #LightCyan {
    ' pool: 3Pool
    assets: DAI, USDC, USDT
    lp token: 3Crv
}

object "FRAX+3Crv" as frax3Crv <<Curve>> #LightCyan {
    ' pool: 3Pool
    assets: FRAX, 3Crv
    lp token: FRAX3CRV-f
}

object "mUSD+3Crv" as musd3Crv <<Curve>> #LightCyan {
    ' pool: mUSD+3Crv
    assets: musd, 3CRV
    lp token: musd3CRV
}

object "BUSD+3Crv" as busd3Crv <<Curve>> #LightCyan {
    ' pool: USDP+3Crv
    assets: BUSD, 3Crv
    lp token: cvxBUSD3CRV-f
}

object "LUSD+3Crv" as lusd3Crv <<Curve>> #LightCyan {
    ' pool: USDP+3Crv
    assets: LUSD, 3Crv
    lp token: LUSD3CRV-f
}

object "FRAX+3Crv" as cvx1 <<Convex>> #Thistle {
    ' pool: FRAX+3Crv
    asset: FRAX3CRV-f
    lp token: cvxcrvFRAX
}

object "mUSD+3Crv" as cvx2 <<Convex>> #Thistle {
    ' pool: mUSD+3Crv
    asset: musd3CRV
    lp token: cvxmusd3CRV
}

object "BUSD+3Crv" as cvx3 <<Convex>> #Thistle {
    ' pool: USDP+3Crv
    asset: BUSD3CRV-f
    lp token: cvxBUSD3CRV-f
}

object "LUSD+3Crv" as cvx4 <<Convex>> #Thistle {
    ' pool: USDP+3Crv
    asset: LUSD3CRV-f
    lp token: cvxLUSD3CRV-f
}

' object "sUSD+3Crv" as cvx5 <<Convex>> #Thistle {
'     ' pool: USDP+3Crv
'     asset: crvPlain3andSUSD
'     lp token: cvxcrvPlain3andSUSD
' }

object "FRAX Gauge" as cg1 <<Curve>> #LightCyan {
    asset: FRAX3CRV-f
}

object "mUSD Gauge" as cg2 <<Curve>> #LightCyan {
    asset: musd3CRV
}

object "BUSD Gauge" as cg3 <<Curve>> #LightCyan {
    asset: BUSD3CRV-f
}

object "LUSD Gauge" as cg4 <<Curve>> #LightCyan {
    asset: LUSD3CRV-f
}

' object "sUSD Gauge" as cg5 <<Curve>> #LightCyan {
'     asset: crvPlain3andSUSD
' }

mv1 ..> 3p
mv2 ..> 3p
mv3 ..> 3p

mv4 .> 3p

mv1 ..> mv4
mv2 ..> mv4
mv3 ..> mv4

mv4 ..> bv1
mv4 ..> bv2
mv4 ..> bv3
mv4 ..> bv4
' mv4 ..> bv5

bv1 <..> l
bv2 <..> l
bv3 <..> l
bv4 <..> l
' bv5 <..> al

bv1 ....> cvx1
bv2 ....> cvx2
bv3 ....> cvx3
bv4 ....> cvx4
' bv5 ...> cvx5

bv1 ...> frax3Crv
bv2 ...> musd3Crv
bv3 ...> busd3Crv
bv4 ...> lusd3Crv
' bv5 ...> sUSD3Crv

3p <.. bv1
3p <.. bv2
3p <.. bv3
3p <.. bv4
' 3p <.. bv5

cvx1 ..> cg1
cvx2 ..> cg2
cvx3 ..> cg3
cvx4 ..> cg4
' cvx5 ..> cg5

frax3Crv <... cg1
musd3Crv <... cg2
busd3Crv <... cg3
lusd3Crv <... cg4
' sUSD3Crv <... cg5

frax3Crv <.. cvx1
musd3Crv <.. cvx2
busd3Crv <.. cvx3
lusd3Crv <.. cvx4
' sUSD3Crv <... cvx5

l <.> css
css <.> cs

@enduml
